### ISSUE TITLE
it looks like this site is dead(?)

### ISSUE THREAD

**Issue by M0REKZ** [colenh/rickrollnt#4]
rickrolled.com/

:T?

<img width="1007" alt="Captura de Pantalla 2022-09-04 a la(s) 19 53 46" src="https://user-images.githubusercontent.com/60852359/188338394-2e59a047-9bb3-4737-a3fe-aad26f7e834d.png">

**Comment by colenh** [comment]
looks like it, will remove soon!
thank u
